require('./src/styles/global.scss')
// require('./src/styles/bulma.scss')
// require("prismjs/themes/prism-okaidia.css")
require("prismjs/themes/prism-solarizedlight.css")
// require("prismjs/plugins/line-numbers/prism-line-numbers.css")